CREATE TYPE "role" AS ENUM (
  'client',
  'employee'
);

CREATE TYPE "status" AS ENUM (
  'available',
  'disabled'
);

CREATE TYPE "process" AS ENUM (
  'pending',
  'cancelled',
  'completed'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(60) NOT NULL,
  "email" varchar(90) UNIQUE NOT NULL,
  "password" varchar(90) NOT NULL,
  "role" role DEFAULT 'client',
  "status" status DEFAULT 'available'
);

CREATE TABLE "repairs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "date" timestamp,
  "status" process DEFAULT 'pending',
  "user_id" integer
);

ALTER TABLE "repairs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
